### ISSUE TITLE
MassActions are not working

### ISSUE THREAD

**Issue by pantaoran** [ashsmith/magento2-blog-module-tutorial#10]
I'm using the Magento 2.0.0 release and followed your tutorial, thanks for that!

It seems that you must have missed the massactions in your testing? The dropdown on top of the grid in the backend contains nothing.
I changed the <massactions> section in view/adminhtml/ui_component/blog_post_listing.xml to match the formats that I see in core modules and now the dropdown contains values, but when I try to execute these actions there are exceptions in AbstractMassStatus.php.

Also another question, are you ever going to finish the tutorial part about unit testing?

**Comment by tanberry** [comment]
Tutorial about unit testing?? I am all ears! @ashsmith I'd like to learn more about this and see if you are interested in helping out the official Magento DevDocs team with some content about unit testing. This is an area we are lacking...
