### ISSUE TITLE
Disabled posts cannot be edited

### ISSUE THREAD

**Issue by pantaoran** [ashsmith/magento2-blog-module-tutorial#12]
It's me yet again, I find that editing disabled posts is impossible in the current state with Magento 2.0.0 release.

The shown error says "This post no longer exists."
It's not surprising, since in https://github.com/ashsmith/magento2-blog-module-tutorial/blob/master/Model/ResourceModel/Post.php you override _getLoadSelect(...) so that only enabled posts can be loaded. Not sure what you were thinking there...

**Comment by ashsmith** [comment]
To add to this, disabled posts still appear on the frontend, which isn't expected functionality.
