### ISSUE TITLE
Missing CollectionFactory?

### ISSUE THREAD

**Issue by mybinaryromance** [ashsmith/magento2-blog-module-tutorial#17]
In Ashsmith\Blog\Block\PostList on line 24 you use \Ashsmith\Blog\Model\ResourceModel\Post\CollectionFactory - but this class does not seem to exist. Can this be fixed just by renaming \Ashsmith\Blog\Model\ResourceModel\Post\Collection to \Ashsmith\Blog\Model\ResourceModel\Post\CollectionFactory?

Great Tutorial! Thx!

**Comment by ashsmith** [comment]
@mybinaryromance Factory classes are generated by Magento automatically. You can read up on how this works over on the Magento 2 dev docs: http://devdocs.magento.com/guides/v2.0/extension-dev-guide/code-generation.html

Thanks :)

**Comment by ashsmith** [comment]
I'll raise this as an issue over on my blog, and make sure the tutorial covers code generation
