### ISSUE TITLE
Unused class variable / Typo

### ISSUE THREAD

**Issue by MaximumP** [ashsmith/magento2-blog-module-tutorial#19]
First of all thanks for that great tutorial.
I think you just used the wrong variable in the `__construct` and `execute` method in the file

**magento2-blog-module-tutorial/Controller/View/Index.php**

The class variable is named `$resultPageFactory` but in the following code you refer to a `$resultForwardFactory` variable.

Either the class variable is unused or you used the wrong variable.

**Comment by ashsmith** [comment]
You're absolutely right. Looks like something I missed during a refactor. Thanks for spotting!
