### ISSUE TITLE
Ashsmith\Blog\Block\Adminhtml\Post\Grid\Renderer\Action\UrlBuilder is not exsist

### ISSUE THREAD

**Issue by refaelgold** [ashsmith/magento2-blog-module-tutorial#2]
Class Gold\Blog\Block\Adminhtml\Post\Grid\Renderer\Action\UrlBuilder does not exist

any chance to fix it?

**Comment by refaelgold** [comment]
Hey!! i just see you unlink the admin panel

i waiting for it :))
Really like your Blog

keep up your Awesome  Tutorials!!!!

**Comment by ashsmith** [comment]
Fixed in the latest release (0.5.2) https://github.com/ashsmith/magento2-blog-module-tutorial/releases/tag/0.5.2-stable

Thanks for submitting an issue :)
