### ISSUE TITLE
wrong xsi:noNamespaceSchemaLocation

### ISSUE THREAD

**Issue by sakiss** [ashsmith/magento2-blog-module-tutorial#3]
In the file view/adminhtml/ui_component/blog_post_listing.xml the correct path for the xsi:noNamespaceSchemaLocation is that:

_xsi:noNamespaceSchemaLocation="../../../../../Magento/Ui/etc/ui_configuration.xsd">_

**Comment by ashsmith** [comment]
Good spot. Fixed. Thank you
