### ISSUE TITLE
Error in the backend

### ISSUE THREAD

**Issue by sakiss** [ashsmith/magento2-blog-module-tutorial#6]
Backend gives that:

Recoverable Error: Argument 1 passed to Magento\Framework\Exception\LocalizedException::__construct() must be an instance of Magento\Framework\Phrase, string given, called in /var/www/html/magento2/lib/internal/Magento/Framework/View/Element/UiComponent/Config/DomMerger.php on line 327 and defined in /var/www/html/magento2/lib/internal/Magento/Framework/Exception/LocalizedException.php on line 31

Seems like an issue with the ui-component xml

**Comment by ashsmith** [comment]
I'll investigate this later today, haven't experienced this myself though

**Comment by ashsmith** [comment]
Was never able to reproduce this issue. Working with the latest Magento 2 release. Closing :)
