### ISSUE TITLE
@TODO

### ISSUE THREAD

**Issue by tronghuan** [ashsmith/magento2-blog-module-tutorial#7]
Hi Ash Smith,

This is not an issue, but I really want to see you will write it as soon.

/**
     \* Return the desired URL of a post
     \*  eg: /blog/view/index/id/1/
     \* @TODO Move to a PostUrl model, and make use of the
     \* @TODO rewrite system, using url_key to build url.
     \* @TODO desired url: /blog/my-latest-blog-post-title
     *
     \* @return string
     */

Thank you so much.

**Comment by ashsmith** [comment]
Done in my last commit :)
