### ISSUE TITLE
Not registered handle blog_post_listing_data_source

### ISSUE THREAD

**Issue by michaelcoleweb** [ashsmith/magento2-blog-module-tutorial#8]
When trying to access the grid page, I get the error 'Not registered handle blog_post_listing_data_source'

**Comment by ashsmith** [comment]
Looking into this today. It's likely an issue with the latest release and me not keeping up to date :)

**Comment by michaelcoleweb** [comment]
Cheers, tried comparing it to the cms module and haven't been able to see anything that stands out

**Comment by ashsmith** [comment]
Issue resolved in the last commit on master :) 5.3.0-stable

**Comment by raoraafe** [comment]
what was the issue?

**Comment by ashsmith** [comment]
You can view the diff here: https://github.com/ashsmith/magento2-blog-module-tutorial/commit/a19eae05531ff7dd0c638fcd63a99d5de6050844#diff-8564704260549e71a21bcfaef977ef33R27

Lines 24-30 were missing. They register the handle

**Comment by phanxuanphucnd** [comment]
can you show code ?
